---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=6144"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.14
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        types:
          - python
        require_serial: true
        entry: uv run mypy
