"""IAB categories data."""

# IAB Content Taxonomy 1.0 mapping from category name to code
# Source: https://github.com/InteractiveAdvertisingBureau/Taxonomies/blob/develop/Content%20Taxonomies/Content%20Taxonomy%201.0.tsv
CATEGORIES = {
    "Arts & Entertainment": "IAB1",
    "Books & Literature": "IAB1-1",
    "Celebrity Fan/Gossip": "IAB1-2",
    "Fine Art": "IAB1-3",
    "Humor": "IAB1-4",
    "Movies": "IAB1-5",
    "Music": "IAB1-6",
    "Television": "IAB1-7",
    "Automotive": "IAB2",
    "Auto Parts": "IAB2-1",
    "Auto Repair": "IAB2-2",
    "Buying/Selling Cars": "IAB2-3",
    "Car Culture": "IAB2-4",
    "Certified Pre-Owned": "IAB2-5",
    "Convertible": "IAB2-6",
    "Coupe": "IAB2-7",
    "Crossover": "IAB2-8",
    "Diesel": "IAB2-9",
    "Electric Vehicle": "IAB2-10",
    "Hatchback": "IAB2-11",
    "Hybrid": "IAB2-12",
    "Luxury": "IAB2-13",
    "MiniVan": "IAB2-14",
    "Motorcycles": "IAB2-15",
    "Off-Road Vehicles": "IAB2-16",
    "Performance Vehicles": "IAB2-17",
    "Pickup": "IAB2-18",
    "Road-Side Assistance": "IAB2-19",
    "Sedan": "IAB2-20",
    "Trucks & Accessories": "IAB2-21",
    "Vintage Cars": "IAB2-22",
    "Wagon": "IAB2-23",
    "Business": "IAB3",
    "Advertising": "IAB3-1",
    "Agriculture": "IAB3-2",
    "Biotech/Biomedical": "IAB3-3",
    "Business Software": "IAB3-4",
    "Construction": "IAB3-5",
    "Forestry": "IAB3-6",
    "Government": "IAB3-7",
    "Green Solutions": "IAB3-8",
    "Human Resources": "IAB3-9",
    "Logistics": "IAB3-10",
    "Marketing": "IAB3-11",
    "Metals": "IAB3-12",
    "Careers": "IAB4",
    "Career Planning": "IAB4-1",
    "College": "IAB4-2",
    "Financial Aid": "IAB4-3",
    "Job Fairs": "IAB4-4",
    "Job Search": "IAB4-5",
    "Resume Writing/Advice": "IAB4-6",
    "Nursing": "IAB4-7",
    "Scholarships": "IAB4-8",
    "Telecommuting": "IAB4-9",
    "U.S. Military": "IAB4-10",
    "Career Advice": "IAB4-11",
    "Education": "IAB5",
    "41832 Education": "IAB5-1",
    "Adult Education": "IAB5-2",
    "Art History": "IAB5-3",
    "Colledge Administration": "IAB5-4",
    "College Life": "IAB5-5",
    "Distance Learning": "IAB5-6",
    "English as a 2nd Language": "IAB5-7",
    "Language Learning": "IAB5-8",
    "Graduate School": "IAB5-9",
    "Homeschooling": "IAB5-10",
    "Homework/Study Tips": "IAB5-11",
    "K-6 Educators": "IAB5-12",
    "Private School": "IAB5-13",
    "Special Education": "IAB5-14",
    "Studying Business": "IAB5-15",
    "Family & Parenting": "IAB6",
    "Adoption": "IAB6-1",
    "Babies & Toddlers": "IAB6-2",
    "Daycare/Pre School": "IAB6-3",
    "Family Internet": "IAB6-4",
    "Parenting - K-6 Kids": "IAB6-5",
    "Parenting teens": "IAB6-6",
    "Pregnancy": "IAB6-7",
    "Special Needs Kids": "IAB6-8",
    "Eldercare": "IAB6-9",
    "Health & Fitness": "IAB7",
    "Exercise": "IAB7-1",
    "A.D.D.": "IAB7-2",
    "AIDS/HIV": "IAB7-3",
    "Allergies": "IAB7-4",
    "Alternative Medicine": "IAB7-5",
    "Arthritis": "IAB7-6",
    "Asthma": "IAB7-7",
    "Autism/PDD": "IAB7-8",
    "Bipolar Disorder": "IAB7-9",
    "Brain Tumor": "IAB7-10",
    "Cancer": "IAB7-11",
    "Cholesterol": "IAB7-12",
    "Chronic Fatigue Syndrome": "IAB7-13",
    "Chronic Pain": "IAB7-14",
    "Cold & Flu": "IAB7-15",
    "Deafness": "IAB7-16",
    "Dental Care": "IAB7-17",
    "Depression": "IAB7-18",
    "Dermatology": "IAB7-19",
    "Diabetes": "IAB7-20",
    "Epilepsy": "IAB7-21",
    "GERD/Acid Reflux": "IAB7-22",
    "Headaches/Migraines": "IAB7-23",
    "Heart Disease": "IAB7-24",
    "Herbs for Health": "IAB7-25",
    "Holistic Healing": "IAB7-26",
    "IBS/Crohn's Disease": "IAB7-27",
    "Incest/Abuse Support": "IAB7-28",
    "Incontinence": "IAB7-29",
    "Infertility": "IAB7-30",
    "Men's Health": "IAB7-31",
    "Nutrition": "IAB7-32",
    "Orthopedics": "IAB7-33",
    "Panic/Anxiety Disorders": "IAB7-34",
    "Pediatrics": "IAB7-35",
    "Physical Therapy": "IAB7-36",
    "Psychology/Psychiatry": "IAB7-37",
    "Senior Health": "IAB7-38",
    "Sexuality": "IAB7-39",
    "Sleep Disorders": "IAB7-40",
    "Smoking Cessation": "IAB7-41",
    "Substance Abuse": "IAB7-42",
    "Thyroid Disease": "IAB7-43",
    "Weight Loss": "IAB7-44",
    "Women's Health": "IAB7-45",
    "Food & Drink": "IAB8",
    "American Cuisine": "IAB8-1",
    "Barbecues & Grilling": "IAB8-2",
    "Cajun/Creole": "IAB8-3",
    "Chinese Cuisine": "IAB8-4",
    "Cocktails/Beer": "IAB8-5",
    "Coffee/Tea": "IAB8-6",
    "Cuisine-Specific": "IAB8-7",
    "Desserts & Baking": "IAB8-8",
    "Dining Out": "IAB8-9",
    "Food Allergies": "IAB8-10",
    "French Cuisine": "IAB8-11",
    "Health/Lowfat Cooking": "IAB8-12",
    "Italian Cuisine": "IAB8-13",
    "Japanese Cuisine": "IAB8-14",
    "Mexican Cuisine": "IAB8-15",
    "Vegan": "IAB8-16",
    "Vegetarian": "IAB8-17",
    "Wine": "IAB8-18",
    "Hobbies & Interests": "IAB9",
    "Art/Technology": "IAB9-1",
    "Arts & Crafts": "IAB9-2",
    "Beadwork": "IAB9-3",
    "Birdwatching": "IAB9-4",
    "Board Games/Puzzles": "IAB9-5",
    "Candle & Soap Making": "IAB9-6",
    "Card Games": "IAB9-7",
    "Chess": "IAB9-8",
    "Cigars": "IAB9-9",
    "Collecting": "IAB9-10",
    "Comic Books": "IAB9-11",
    "Drawing/Sketching": "IAB9-12",
    "Freelance Writing": "IAB9-13",
    "Genealogy": "IAB9-14",
    "Getting Published": "IAB9-15",
    "Guitar": "IAB9-16",
    "Home Recording": "IAB9-17",
    "Investors & Patents": "IAB9-18",
    "Jewelry Making": "IAB9-19",
    "Magic & Illusion": "IAB9-20",
    "Needlework": "IAB9-21",
    "Painting": "IAB9-22",
    "Photography": "IAB9-23",
    "Radio": "IAB9-24",
    "Roleplaying Games": "IAB9-25",
    "Sci-Fi & Fantasy": "IAB9-26",
    "Scrapbooking": "IAB9-27",
    "Screenwriting": "IAB9-28",
    "Stamps & Coins": "IAB9-29",
    "Video & Computer Games": "IAB9-30",
    "Woodworking": "IAB9-31",
    "Home & Garden": "IAB10",
    "Appliances": "IAB10-1",
    "Entertaining": "IAB10-2",
    "Environmental Safety": "IAB10-3",
    "Gardening": "IAB10-4",
    "Home Repair": "IAB10-5",
    "Home Theater": "IAB10-6",
    "Interior Decorating": "IAB10-7",
    "Landscaping": "IAB10-8",
    "Remodeling & Construction": "IAB10-9",
    "Law, Gov't & Politics": "IAB11",
    "Immigration": "IAB11-1",
    "Legal Issues": "IAB11-2",
    "U.S. Government Resources": "IAB11-3",
    "Politics": "IAB11-4",
    "Commentary": "IAB11-5",
    "News": "IAB12",
    "International News": "IAB12-1",
    "National News": "IAB12-2",
    "Local News": "IAB12-3",
    "Personal Finance": "IAB13",
    "Beginning Investing": "IAB13-1",
    "Credit/Debt & Loans": "IAB13-2",
    "Financial News": "IAB13-3",
    "Financial Planning": "IAB13-4",
    "Hedge Fund": "IAB13-5",
    "Insurance": "IAB13-6",
    "Investing": "IAB13-7",
    "Mutual Funds": "IAB13-8",
    "Options": "IAB13-9",
    "Retirement Planning": "IAB13-10",
    "Stocks": "IAB13-11",
    "Tax Planning": "IAB13-12",
    "Society": "IAB14",
    "Dating": "IAB14-1",
    "Divorce Support": "IAB14-2",
    "Gay Life": "IAB14-3",
    "Marriage": "IAB14-4",
    "Senior Living": "IAB14-5",
    "Teens": "IAB14-6",
    "Weddings": "IAB14-7",
    "Ethnic Specific": "IAB14-8",
    "Science": "IAB15",
    "Astrology": "IAB15-1",
    "Biology": "IAB15-2",
    "Chemistry": "IAB15-3",
    "Geology": "IAB15-4",
    "Paranormal Phenomena": "IAB15-5",
    "Physics": "IAB15-6",
    "Space/Astronomy": "IAB15-7",
    "Geography": "IAB15-8",
    "Botany": "IAB15-9",
    "Weather": "IAB15-10",
    "Pets": "IAB16",
    "Aquariums": "IAB16-1",
    "Birds": "IAB16-2",
    "Cats": "IAB16-3",
    "Dogs": "IAB16-4",
    "Large Animals": "IAB16-5",
    "Reptiles": "IAB16-6",
    "Veterinary Medicine": "IAB16-7",
    "Sports": "IAB17",
    "Auto Racing": "IAB17-1",
    "Baseball": "IAB17-2",
    "Bicycling": "IAB17-3",
    "Bodybuilding": "IAB17-4",
    "Boxing": "IAB17-5",
    "Canoeing/Kayaking": "IAB17-6",
    "Cheerleading": "IAB17-7",
    "Climbing": "IAB17-8",
    "Cricket": "IAB17-9",
    "Figure Skating": "IAB17-10",
    "Fly Fishing": "IAB17-11",
    "Football": "IAB17-12",
    "Freshwater Fishing": "IAB17-13",
    "Game & Fish": "IAB17-14",
    "Golf": "IAB17-15",
    "Horse Racing": "IAB17-16",
    "Horses": "IAB17-17",
    "Hunting/Shooting": "IAB17-18",
    "Inline Skating": "IAB17-19",
    "Martial Arts": "IAB17-20",
    "Mountain Biking": "IAB17-21",
    "NASCAR Racing": "IAB17-22",
    "Olympics": "IAB17-23",
    "Paintball": "IAB17-24",
    "Power & Motorcycles": "IAB17-25",
    "Pro Basketball": "IAB17-26",
    "Pro Ice Hockey": "IAB17-27",
    "Rodeo": "IAB17-28",
    "Rugby": "IAB17-29",
    "Running/Jogging": "IAB17-30",
    "Sailing": "IAB17-31",
    "Saltwater Fishing": "IAB17-32",
    "Scuba Diving": "IAB17-33",
    "Skateboarding": "IAB17-34",
    "Skiing": "IAB17-35",
    "Snowboarding": "IAB17-36",
    "Surfing/Bodyboarding": "IAB17-37",
    "Swimming": "IAB17-38",
    "Table Tennis/Ping-Pong": "IAB17-39",
    "Tennis": "IAB17-40",
    "Volleyball": "IAB17-41",
    "Walking": "IAB17-42",
    "Waterski/Wakeboard": "IAB17-43",
    "World Soccer": "IAB17-44",
    "Style & Fashion": "IAB18",
    "Beauty": "IAB18-1",
    "Body Art": "IAB18-2",
    "Fashion": "IAB18-3",
    "Jewelry": "IAB18-4",
    "Clothing": "IAB18-5",
    "Accessories": "IAB18-6",
    "Technology & Computing": "IAB19",
    "3-D Graphics": "IAB19-1",
    "Animation": "IAB19-2",
    "Antivirus Software": "IAB19-3",
    "C/C++": "IAB19-4",
    "Cameras & Camcorders": "IAB19-5",
    "Cell Phones": "IAB19-6",
    "Computer Certification": "IAB19-7",
    "Computer Networking": "IAB19-8",
    "Computer Peripherals": "IAB19-9",
    "Computer Reviews": "IAB19-10",
    "Data Centers": "IAB19-11",
    "Databases": "IAB19-12",
    "Desktop Publishing": "IAB19-13",
    "Desktop Video": "IAB19-14",
    "Email": "IAB19-15",
    "Graphics Software": "IAB19-16",
    "Home Video/DVD": "IAB19-17",
    "Internet Technology": "IAB19-18",
    "Java": "IAB19-19",
    "JavaScript": "IAB19-20",
    "Mac Support": "IAB19-21",
    "MP3/MIDI": "IAB19-22",
    "Net Conferencing": "IAB19-23",
    "Net for Beginners": "IAB19-24",
    "Network Security": "IAB19-25",
    "Palmtops/PDAs": "IAB19-26",
    "PC Support": "IAB19-27",
    "Portable": "IAB19-28",
    "Entertainment": "IAB19-29",
    "Shareware/Freeware": "IAB19-30",
    "Unix": "IAB19-31",
    "Visual Basic": "IAB19-32",
    "Web Clip Art": "IAB19-33",
    "Web Design/HTML": "IAB19-34",
    "Web Search": "IAB19-35",
    "Windows": "IAB19-36",
    "Travel": "IAB20",
    "Adventure Travel": "IAB20-1",
    "Africa": "IAB20-2",
    "Air Travel": "IAB20-3",
    "Australia & New Zealand": "IAB20-4",
    "Bed & Breakfasts": "IAB20-5",
    "Budget Travel": "IAB20-6",
    "Business Travel": "IAB20-7",
    "By US Locale": "IAB20-8",
    "Camping": "IAB20-9",
    "Canada": "IAB20-10",
    "Caribbean": "IAB20-11",
    "Cruises": "IAB20-12",
    "Eastern Europe": "IAB20-13",
    "Europe": "IAB20-14",
    "France": "IAB20-15",
    "Greece": "IAB20-16",
    "Honeymoons/Getaways": "IAB20-17",
    "Hotels": "IAB20-18",
    "Italy": "IAB20-19",
    "Japan": "IAB20-20",
    "Mexico & Central America": "IAB20-21",
    "National Parks": "IAB20-22",
    "South America": "IAB20-23",
    "Spas": "IAB20-24",
    "Theme Parks": "IAB20-25",
    "Traveling with Kids": "IAB20-26",
    "United Kingdom": "IAB20-27",
    "Real Estate": "IAB21",
    "Apartments": "IAB21-1",
    "Architects": "IAB21-2",
    "Buying/Selling Homes": "IAB21-3",
    "Shopping": "IAB22",
    "Contests & Freebies": "IAB22-1",
    "Couponing": "IAB22-2",
    "Comparison": "IAB22-3",
    "Engines": "IAB22-4",
    "Religion & Spirituality": "IAB23",
    "Alternative Religions": "IAB23-1",
    "Atheism/Agnosticism": "IAB23-2",
    "Buddhism": "IAB23-3",
    "Catholicism": "IAB23-4",
    "Christianity": "IAB23-5",
    "Hinduism": "IAB23-6",
    "Islam": "IAB23-7",
    "Judaism": "IAB23-8",
    "Latter-Day Saints": "IAB23-9",
    "Pagan/Wiccan": "IAB23-10",
    "Uncategorized": "IAB24",
    "Non-Standard Content": "IAB25",
    "Unmoderated UGC": "IAB25-1",
    "Extreme Graphic/Explicit Violence": "IAB25-2",
    "Pornography": "IAB25-3",
    "Profane Content": "IAB25-4",
    "Hate Content": "IAB25-5",
    "Under Construction": "IAB25-6",
    "Incentivized": "IAB25-7",
    "Illegal Content": "IAB26",
    # duplicate
    # "Illegal Content": "IAB26-1",
    "Warez": "IAB26-2",
    "Spyware/Malware": "IAB26-3",
    "Copyright Infringement": "IAB26-4",
}

CATEGORIES_REVERSED = {code: name for name, code in CATEGORIES.items()}

CATEGORY_NAMES = [
    # add name of main category before subcategory name to extend the context
    (f"{CATEGORIES_REVERSED[code.split('-')[0]]}: {name}" if "-" in code else name)
    for name, code in CATEGORIES.items()
]
